# Generated by Django 3.2.9 on 2021-12-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_remove_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='myevents', to='levelupapi.Gamer'),
        ),
    ]
