# Generated by Django 3.2.9 on 2021-12-22 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0007_remove_event_attendees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='maker',
        ),
        migrations.AddField(
            model_name='game',
            name='gamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='levelupapi.gamer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='number_of_players',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Experienced'), (3, 'Professional'), (4, 'Expert')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='Monopoly', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelupapi.gamer'),
        ),
    ]
