# Generated by Django 3.2.9 on 2021-12-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0008_auto_20211222_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gametype',
            new_name='game_type',
        ),
        migrations.AlterField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Experienced'), (3, 'Professional'), (4, 'Expert')], default=1),
        ),
    ]
