# Generated by Django 3.2.9 on 2022-01-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0011_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='myevents', to='levelupapi.Gamer'),
        ),
    ]
